### ISSUE TITLE
About CoCoNut

### ISSUE THREAD

**Issue by ShangwenWang** [lin-tan/CoCoNut-Artifact#1]
Dear authors, 
  Congratulations on your new research! It is really a novel and solid work.
  After reading your paper, I am quite interested about this tool. I'd like to know when would you like to open more data (e.g., the source code and experiment result). 
  Thanks a lot.

**Comment by thibolu** [comment]
Hi ShangwenWang, 
We are working on uploading more material. The datasets are already uploaded and the experimental results (i.e., correct patches generated and hyperparameters should follow soon).

Eventually, we also plan to include the trained models and the source code to train or inference, but it will take a bit more time.

**Comment by ShangwenWang** [comment]
Dear @thibolu 
Thanks for your reply and releasing the training data. Now I am confused by the content in the data.
For instance, there are three .txt files in the Python folder but I don't know how to use them. I find the SHAs in the _meta_ file but we should also know some other information (e.g., the repository) if we want to refer to the original file in GitHub.
I would appreciate it if you could provide some help.
Many thanks

**Comment by BBerabi** [comment]
Are the source code to train or inference uploaded or not yet?

**Comment by thibolu** [comment]
@BBerabi , the source code for training and inference has been uploaded.

**Comment by BEbillionaireUSD** [comment]
> Hi ShangwenWang, We are working on uploading more material. The datasets are already uploaded and the experimental results (i.e., correct patches generated and hyperparameters should follow soon).
> 
> Eventually, we also plan to include the trained models and the source code to train or inference, but it will take a bit more time.

Hi, do you still plan to upload more about the experiment results? such as the correct patches generated (or at least their IDs)
