### ISSUE TITLE
Sharing of trained models

### ISSUE THREAD

**Issue by DoHuber** [lin-tan/CoCoNut-Artifact#6]
Dear Authors,

in reference to issue #1, I'd like to ask if you could upload the trained models used in the evaluation of your ISSTA 2020 paper? I am conducting research on the attention mechanism of automatic program repair approaches and would like to include CoCoNuT, but the training from the provided data and sources has proven very resource-demanding, and a pre-trained model could greatly reduce this effort.

Many thanks.

**Comment by DoHuber** [comment]
Closing as per E-Mail exchange.

**Comment by nashid** [comment]
@DoHuber are the pre-trained models available?

**Comment by thibolu** [comment]
@nashid , unfortunately we cannot share the pre-trained models at the moment.
